# Generated by Django 4.0.4 on 2022-11-06 08:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="modelBlog",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("titulo", models.CharField(max_length=70)),
                ("subtitulo", models.CharField(max_length=280)),
                ("seccion", models.CharField(max_length=70)),
                ("contenido", models.CharField(max_length=1120)),
                ("autor", models.CharField(max_length=70)),
                ("fecha", models.DateField(default=datetime.datetime.now)),
                (
                    "imagen",
                    models.ImageField(blank=True, null=True, upload_to="pictures"),
                ),
            ],
        ),
    ]
