# Generated by Django 4.0.4 on 2022-11-08 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_modelblog_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="modelblog",
            name="imagen",
        ),
    ]
